os: osx
osx_image: xcode10.2
language: node_js
node_js: '12'
addons:
  apt:
    packages: 
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
script:
  - npm test
  - npm run dist
