language: node_js
node_js: '12'
os: linux

services:
   - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

before_script:
  - npm install

script:
  - npm test
